set -gx OMF_PATH "$HOME/.config/fish/omf"
source $OMF_PATH/init.fish

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1
set -e fish_function_path[1]
set -x EDIRTOR vim
set -x GDK_BACKEND x11

# vi-mode
fish_vi_key_bindings

# alias
alias vim='nvim'
alias vi='nvim'
alias view='nvim -RM'
alias ls='exa --icons --color=always --group-directories-first'
alias ll='exa -alF --icons --color=always --group-directories-first'
alias la='exa -a --icons --color=always --group-directories-first'
alias l='exa -F --icons --color=always --group-directories-first'
alias mans='tldr'
alias rm='trash'
alias youtube-dl-audio='youtube-dl -x --audio-format flac'
alias run="mvn spring-boot:run"
alias ff="find $PWD -type f"
alias vimdiff='nvim -d'

status --is-login; and begin

  # Login shell initialisation
  

end

status --is-interactive; and begin

  # Abbreviations
  

  # Aliases
  

  # Interactive shell intialisation
  # add completions generated by Home Manager to $fish_complete_path
  begin
    set -l joined (string join " " $fish_complete_path)
    set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
    set -l post_joined (string replace $prev_joined "" $joined)
    set -l prev (string split " " (string trim $prev_joined))
    set -l post (string split " " (string trim $post_joined))
    set fish_complete_path $prev "/home/dlan/.local/share/fish/home-manager_generated_completions" $post
  end
end
